### ISSUE TITLE
root directory

### ISSUE THREAD

**Issue by vitalygoji** [googlecodelabs/codelab-components#40]
Is it possible to drop /codelab-components-master/ in to APACHE root directory and run EVERYTHING from there?
Your demo is looking for polymer components in a root directory but some of us prefer to keep all dependencies in a native /codelab-components-master/  
I tried renaming links but gave up after a while.

**Comment by x1ddos** [comment]
Yeah, polymer components have many dependencies, unfortunately.
@vitalygoji I'm afraid we won't be fixing this issue here but I hope you'll be happy to know we're working on a drop-in replacement using just Custom Elements spec, without Polymer or other frameworks/libs, in https://github.com/googlecodelabs/codelab-elements. See https://github.com/googlecodelabs/codelab-components/issues/49 for more details.

I believe it'll be much easier to manage in cases like this one with the drop-in replacement without Polymer dependencies.
